[package]
name = "example-rust"
version = "0.1.0"
authors = ["John Wass <wassj@ctc.com>"]

[dependencies]
actix = "0.7.0"
futures = "0.1"
tokio = "0.1.7"
tokio-io = "0.1"
tokio-codec = "0.1"
tokio-executor = "0.1"
tokio-reactor = "0.1"
tokio-tcp = "0.1"
tokio-timer = "0.2"
